### PR TITLE
69 account statement section show wrong cost for type fee

### PR DESCRIPTION
**Pull request by parv0888**
## Purpose
Fixes Issue #69 

## Changes
Fixes Issue #69 

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

### CODE REVIEW

**Review by abizjak — APPROVED** [review]
Please bump frontend version. Then merge. Looks good.

**Comment by parv0888** [comment]
> Please bump frontend version. Then merge. Looks good.

done

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Comment by SRConcordium** [comment]
Verified OK in Stagenet, https://stagenet.ccdscan.io/ - transaction cost is appearing correct now.

**Comment by SRConcordium** [comment]
Verified OK in Mainnet.

**Pull request merged**
