### PR TITLE
Change calculation of finalization time to use latest block hash info from block info

### PR DESCRIPTION
**Pull request by schwartz-concordium**
## Purpose

Update calculation of finalization time to work with protocol 6.
* https://concordium.atlassian.net/browse/CBW-1231

## Changes

Currently finalization summaries are queried from the block but one can just look at the latest finalized block hash on the block info returned from get block info node query.

Changes are needed since finalization summaries isn't present in protocol 6. Using latest finalization block hash in
block info is a robust calculation in both old (before protocol 6) and new consensus protocol. 

## Checklist

- [X] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [X] I have performed a self-review of the changes.
- [X] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [X] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

**Review by td202 — APPROVED** [review]
Looks good.

**Comment by schwartz-concordium** [comment]
Before merge, add back finalization time chart which was removed in PR
https://github.com/Concordium/concordium-scan/pull/92

**Comment by schwartz-concordium** [comment]
https://github.com/Concordium/concordium-scan/issues/78

**Comment by schwartz-concordium** [comment]
If this is merged as is, then all blocks, which doesn’t have a finalization time set, will have finalization time set to the first different finalized block hash seen (which is around now) and the latest finalized block hash (which is before protocol 6).

Because of this a lot of block will get finalization time set to several months.

I migration job should be added, such that all blocks which hasn’t set their time should have them correctly set. This should be done by iterating from blocks after protocol 6.

**Comment by schwartz-concordium** [comment]
Close in favour of https://github.com/Concordium/concordium-scan/pull/181 which has migration job

**Pull request closed without merging**
